<a href="https://colab.research.google.com/github/qtuter1997/100-Days-Of-ML-Code/blob/master/d2l/ReducingLearningRate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Learning rate schedule and Adaptive learning rate methods for Deep Learning**

---
The most of methods to optimal model when train deep neural network is use reduce learning rate.

1. Learning Rate schedules
2. Adaptive learning rate methods

Reference tutorial at [here](https://towardsdatascience.com/learning-rate-schedules-and-adaptive-learning-rate-methods-for-deep-learning-2c8f433990d1).

In this tutorial, i train convolutional neural network on [CIFAR10](https://www.cs.toronto.edu/~kriz/cifar.html) using differing learning rate schedules and adaptive learing rate methods to compare their model performance.

---






1. Learning rate schedules

Reducing the learning rate according to a pre-defined schedule.

  Common learning rate schdules include **time-base decay, step decay** and **exponential decay**.
  
*   Constant learning rate
*   Time-base dacay
*   Step decay
*   Exponential decay

In the first half of this tutorial


In [3]:
# Add library
import numpy as np
import math
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.optimizers import SGD, Adam, Adagrad, Adadelta, RMSprop
from tensorflow.keras.models import model_from_json
from tensorflow.keras.callbacks import LearningRateScheduler

tf.__version__

'2.4.1'

Load CIFAR10 data

In [4]:
batch_size = 64 # 2^x to match GPU
num_classes = 10
epochs = 100

# input image demensions
img_row, img_col = 32, 32

# The data, shuffled and split between train and test sets
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()

170500096/170498071 [==============================] - 2s 0us/step


In [5]:
# In example, we only use cat [==3] and dog [==5]
train_picks = np.ravel(np.logical_or(Y_train == 3, Y_train == 5))
test_picks = np.ravel(np.logical_or(Y_test == 3, Y_test == 5))

Y_train = np.array(Y_train[train_picks] == 5, dtype= int)
Y_test = np.array(Y_test[test_picks] == 5, dtype= int)

X_train = X_train[train_picks]
X_test = X_test[test_picks]


X_train: [[[[125 125 116]
   [110 101  91]
   [102  90  83]
   ...
   [202 207 214]
   [200 205 212]
   [202 208 214]]

  [[142 146 142]
   [146 144 139]
   [176 172 170]
   ...
   [195 201 205]
   [198 205 209]
   [204 211 215]]

  [[180 185 183]
   [143 146 146]
   [156 157 157]
   ...
   [122 111 113]
   [139 128 131]
   [158 147 150]]

  ...

  [[104  82  41]
   [101  80  39]
   [101  81  38]
   ...
   [126 103  67]
   [126 103  69]
   [125 101  68]]

  [[104  81  40]
   [105  84  41]
   [109  88  43]
   ...
   [138 113  78]
   [137 113  80]
   [137 112  81]]

  [[105  83  42]
   [108  87  45]
   [115  94  50]
   ...
   [143 117  82]
   [143 116  84]
   [144 116  86]]]


 [[[110 104  97]
   [142 135 118]
   [151 146 120]
   ...
   [ 39  39  39]
   [ 40  40  40]
   [ 38  38  38]]

  [[109 103  95]
   [141 133 115]
   [152 147 119]
   ...
   [ 36  36  37]
   [ 40  40  40]
   [ 36  36  36]]

  [[105  98  90]
   [142 133 114]
   [151 145 117]
   ...
   [ 39  39  41]
   [ 44  44  45]
  

2. Adaptive learning rate methods